#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "       Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "       ${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up HAProxy...\n"

# Backup default HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 424715-web-01 18.234.168.198:80 check
    server 424715-web-02 54.152.232.55:80 check
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "HAProxy configured - Roundrobin On web-01 & web-02"

# Restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

