#!/bin/bash

# Check if the private key already exists
if [ -f school ]; then
  echo "Private key 'school' already exists."
  exit 1
fi

# Generate the RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -N "betty" -f school

# Check if key generation was successful
if [ $? -eq 0 ]; then
  echo "RSA key pair generated successfully."
else
  echo "Error generating RSA key pair."
fi

